[package]
name = "cheetiedotpy/farming-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Components = "sleitnick/component@2.4.6"
Roact = "firere/roact@1.5.0"
Replica = "joshuaclarkelua/replica@1.1.4"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.0.1"